<?php
$pageTitle = "Locally Convex Vector Spaces";
$currentPage = "courses";
include('../../../includes/header-courses.php');
?>

        <article>
          <section class="about-text">
            <header>
              <h2 class="h2 article-title">Courses</h2>
            </header>
            <article class="article-second">
              <h2>Locally Convex Vector Spaces (Lokalkonvexe Vektorräume)</h2>
              
              <p><b>Class Nummer:</b> 250074</p>
              <p><b>Class type:</b> VO (lecture course)</p>
              <p><b>Semester hours:</b> 3</p>
              <p><b>Schedule:</b> Mon, Tue, Thu, 12:00-13:00 Seminarraum 2A310, UZA 2</p>
              <p><b>Start:</b> 6.10.2008</p>
              
              <h3>News:</h3>
              <ul>
                <li>2009-01-30: A complete set of my notes can be found on the board outside my office.<br>
                Exams are possible by individual arrangement anytime starting from end of Jannuary.<br>
                I will only be away Feb. 18-23 and end of April.</li>
                <li>2009-01-29: Joint going out on Fr. 30th, 19:30 at <a href="http://www.falter.at/web/wwei/detail.php?nr=1105&keyword=highlander&ref=(keyword%3Dhighlander%26teil%3D1)" target="_blank">'The Highlander'</a></li>
                <li>2009-01-07: The first lecture in Jannuary is Monday 12th.</li>
                <li>2008-11-11: No lecture on Nov. 13.</li>
                <li>2008-10-22: There will be no lecture in the first week (1st, 2nd, and 4th) of December.</li>
                <li>2008-10-20: There will be no lecture in the first week (3rd, 4th, and 6th) of November.</li>
              </ul>
              
              <h3>Introduction:</h3>
              <p>Generally speaking, functional analysis is that part of analysis which uses the power of topology to derive 
              results on function spaces and on operators acting between them.
              Clearly such results are vital for applications in wide areas
              of analysis, not the least in partial differential equations.</p>
              
              <p>Most treatises start with vector spaces where a topology is induced by a
              norm, giving rise to the theory of Banach spaces. In particular, one derives the
              fundamental theorems of Hahn-Banach (on the extension of linear functionals),
              Banach-Steinhaus (also called uniform boundedness principle) and the
              open mapping as well as the closed graph theorem with Banach's isomorphism theorem
              as a corollary (which states that any bijective continuous operator of Banach 
              spaces already is an isomorphism).</p>
              
              <p>However, many of the function spaces ocurring in analysis cannot be turned into 
              (complete) normed spaces in a reasonable way. Some of these can at least be 
              given the structure of a (complete) metric space (called Frechet space, eg. 
              the spaces of continuous or smooth functions on the real line) which
              is characterized by the fact that their topology is induced by a countable family
              of semi-norms. Other spaces, in particular those used in <a href="http://en.wikipedia.org/wiki/Distribution_(mathematics)"
              target="_blank">distribution theory</a> 
              (most prominently the space of test functions, i.e., the space of smooth functions 
              with compact support), ask for an even more general theory as they cannot be
              turned into Frechet spaces.</p>
              
              <p>On the other end of the scale one has topological vector spaces, i.e., 
              vector spaces carrying a topology such that the operations (of addition 
              and scalar multiplication) are continuous. These spaces, however, turn out to 
              be too general for many purposes, that is to say that they do not allow to prove 
              the strong statements one is interested in.
              As a matter of fact, a very general but still widely useful class is comprised by
              those topological vector spaces that possess a fundamental system of neighborhoods of
              the origin consisting of convex sets. Alternatively these so-called locally convex vector spaces
              can be characterized as those topological vector spaces that allow for their topology to be
              generated by a (not necessarily countable) family of semi-norms. The existence of a convex 
              base of zero-neighbourhoods is strong enough for the Hahn-Banach theorem to hold, yielding 
              a sufficiently rich theory of continuous linear functionals and allows, in particular, 
              for a toplogical theory of the function spaces relevant in distribution theory.</p>
              
              <p>In fact, historically, the space of test functions with the appropriate notion of convergence
              was introduced by L. Schwartz before a proper topological description was available. It was the
              success of distribution theory which stimulated the development of the theory of locally convex vector
              spaces and later on both theories evolved in parallel with significant mutual impact.</p>
              
              <p>A slightly extended version of the above text is available 
              <a href="lcvs_theme.pdf">here</a>.</p>
              
              <h3>Contents:</h3>
              <p>This course will introduce you to the theory of locally
              convex vector spaces. The main topics are</p>
              <ul>
                <li>topological vector spaces</li>
                <li>locally convex vector spaces and vector spaces with semi-norms</li>
                <li>projective and inductive limits</li>
                <li>nuclear spaces</li>
                <li>duality</li>
              </ul>
              
              <h3>Literature:</h3>
              <p>I have prepared a short <a href="literature_lcvs.pdf">commented list of books</a> on the topic,
              although we will not strictly follow one of these. The most I am influenced
              by earlier lecture courses by <a href="http://plone.mat.univie.ac.at/people/details?memberid=89&is_guest=0" 
              target="_blank">Michael Grosser</a>, which themselves were influenced by H. Schaefer's "Topological Vector 
              Spaces" (2nd ed., Springer GTM, New York, 1999).</p>
              
              <h3>What you already should know:</h3>
              <p>Prerequisites for this course are</p>
              <ul>
                <li>a good knowledge of basic functional analysis---approximately a three-hours course, eg.
                <a href="../WS0708/fa.html">Funktionalanalysis 1</a>. (An advanced course on Banach or Hilbert space
                theory, in particular spectral theory, is not needed, although you will benefit from some preknowledge 
                on weak convergence and related matters. In this sense this course is _not_ a direct follow up of summer 
                term's <a href="../SoSem08/fa2.html">Functional Analysis 2</a>.)</li>
                <li>a solid basis in general topology---approximately a two-hours course, eg. 
                <a href="http://online.univie.ac.at/vlvz?lvnr=250476&semester=W2006&include=kurzkommentar,leistungskontrolle,voraussetzung,literatur,methoden&exclude=inf_link">Grundbegriffe der Topologie</a>. (Nevertheless we will briefly recall more advanced
                topics of topology at the place where they are first needed.)</li>
              </ul>
              <p>Finally, as always, a good background in analysis is profitable.</p>
              
              <h3>Target audience:</h3>
              <p>This course is primarily designed
              for advanced diploma students or master students, but
              also Ph.D. students will benefit from it. In particlar, people
              knowing distribution theory but who have never been
              introduced into the topological aspects of the theory might
              be interested.</p>
              
              <h3>Related Courses:</h3>
              <p><a href="http://www.mat.univie.ac.at/~gue" target="_blank">Günther Hörmann</a> 
              and I plan to teach a joint course on 
              the theory of distributions in summer term. It will not be designed as continuation 
              of this course but will be quite related.</p>
              
              <h3>Administrative Remarks:</h3>
              <p>The course will normally be held 4 hours (i.e., 4x45=180 mins.) 
              a week but suspended some weeks on (duly) announcement. The language of instruction will
              be English (since I expect some foreign students attending).</p>
              
              <h3>Position within curriculum:</h3>
              <p>Diplomstudium Mathematik, 2. Abschnitt, Studienschwerpunkt Analysis.</p>
              
              <h3>Exams:</h3>
              <p>oral; by arrangement. Further informations will be given on time.</p>
            </article>
          </section>
        </article>

<?php
include('../../../includes/footer-courses.php');
?>