<header>
    <h2 class="h2 article-title">Contact</h2>
  </header>

  <section class="timeline">
    <div class="title-wrapper">
      <div class="icon-box">
        <i class="ph ph-at"></i>
      </div>

      <h3 class="h3"></h3>
    </div>

    <ol class="timeline-list">
      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">Mailing Address</h4>

        <span>Fakultät für Mathematik, Oskar-Morgenstern-Platz 1, 1090 Wien, Austria</span>
      </li>

      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">Office</h4>

        <span>OMP1, Oskar-Morgenstern-Platz 1, Room 10.126</span>
      </li>

      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">Office hours</h4>

        <span>by appointment</span>
      </li>

      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">Phone</h4>

        <span>+43 1 4277-50682</span>
      </li>

      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">Mobile</h4>

        <span>+43 660-8960667</span>
      </li>

      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">E-Mail</h4>

        <span><a href="mailto:roland.steinbauer@univie.ac.at">roland.steinbauer@univie.ac.at</a></span>
      </li>

      <li class="timeline-item">
        <h4 class="h4 timeline-item-title">Website</h4>

        <span>
          <a href="../about/about.php">Personal page</a>,
          <a href="https://ufind.univie.ac.at/de/person.html?id=5458" target="_blank">official university page</a>
        </span>
      </li>
    </ol>
  </section>

  <section class="mapbox">
    <div id="map-consent-banner">
      <p>This map is powered by <a target="_blank" href="https://osmfoundation.org/wiki/Privacy_Policy">OpenStreetMap</a>. Click "Accept" to load the map.</p>
      <button id="accept-map-btn">Accept</button>
    </div>
    <div id="map-container" style="display: none;"></div>
  </section>

  <script src="/assets/js/contact-map.js" defer></script>
